security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
            logout:
                path: logout
                target: /

    access_control:
    - { path: ^/covoiturages, roles: PUBLIC_ACCESS }  # Remplacez IS_AUTHENTICATED_ANONYMOUSLY
    - { path: ^/covoiturages/recherche, roles: PUBLIC_ACCESS }  # Ajoutez cette ligne
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/employe, roles: ROLE_EMPLOYE }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/$, roles: PUBLIC_ACCESS }  # Autorise l'accès à la home
